#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh — first-time setup for raycast-infra-scripts
# Run this once after cloning the repository.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

CONFIG_DIR="$HOME/.config/raycast-infra"
CONFIG_FILE="$CONFIG_DIR/config"

echo ""
echo "┌─────────────────────────────────────────────────────┐"
echo "│   raycast-infra-scripts — Setup                     │"
echo "└─────────────────────────────────────────────────────┘"
echo ""

# ── Check Python ───────────────────────────────────────────────────────────────
echo "Checking prerequisites..."
echo ""

if command -v python3 &>/dev/null; then
    PY_VERSION=$(python3 --version 2>&1)
    echo "  ✓ Python found: $PY_VERSION"
else
    echo "  ✗ python3 not found."
    echo ""
    echo "  Install it first, then run setup.sh again:"
    echo ""
    echo "    1. Install Homebrew (if you don't have it):"
    echo "       /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    echo ""
    echo "    2. Install Python:"
    echo "       brew install python"
    echo ""
    exit 1
fi

# ── Find infra repo ────────────────────────────────────────────────────────────
COMMON_PATHS=(
    "$HOME/projects/infra"
    "$HOME/work/infra"
    "$HOME/code/infra"
    "$HOME/projects/infrastructure"
    "$HOME/work/infrastructure"
    "$HOME/code/infrastructure"
    "$HOME/infra"
    "$HOME/dev/infra"
    "$HOME/src/infra"
)

DETECTED=""
for p in "${COMMON_PATHS[@]}"; do
    if [[ -d "$p/accounts" ]]; then
        DETECTED="$p"
        break
    fi
done

echo ""
if [[ -n "$DETECTED" ]]; then
    echo "  ✓ Found infra repo at: $DETECTED"
    echo ""
    read -rp "  Use this path? [Y/n] " CONFIRM
    CONFIRM="${CONFIRM:-Y}"
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        DETECTED=""
    fi
fi

if [[ -z "$DETECTED" ]]; then
    echo ""
    echo "  Enter the full path to your infrastructure repo:"
    echo "  (the directory that contains an 'accounts/' folder)"
    echo ""
    read -rp "  Path: " DETECTED
    DETECTED="${DETECTED/#\~/$HOME}"

    if [[ ! -d "$DETECTED/accounts" ]]; then
        echo ""
        echo "  ✗ No 'accounts/' directory found at: $DETECTED"
        echo "  Please check the path and run setup.sh again."
        exit 1
    fi
fi

# ── Write config ───────────────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# raycast-infra-scripts configuration
# Generated by setup.sh on $(date)

INFRA_REPO_PATH=$DETECTED
EOF

echo ""
echo "  ✓ Config saved to: $CONFIG_FILE"

# ── Make scripts executable ────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
chmod +x "$SCRIPT_DIR"/scripts/*.sh
echo "  ✓ Scripts marked as executable"

# ── Quick test ─────────────────────────────────────────────────────────────────
echo ""
echo "Running a quick test..."
echo ""

if INFRA_REPO_PATH="$DETECTED" python3 "$SCRIPT_DIR/zone-lookup.py" --list > /dev/null 2>&1; then
    ZONE_COUNT=$(INFRA_REPO_PATH="$DETECTED" python3 "$SCRIPT_DIR/zone-lookup.py" --list 2>/dev/null | wc -l | tr -d ' ')
    echo "  ✓ Found $ZONE_COUNT zones."
else
    echo "  ✗ Test failed — could not parse zones from: $DETECTED"
    echo "  Make sure the repo is fully cloned and your path is correct."
    exit 1
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo "┌─────────────────────────────────────────────────────┐"
echo "│   Setup complete!                                    │"
echo "│                                                      │"
echo "│   Last step: add scripts/ folder to Raycast.        │"
echo "│   See README.md → Step 4 for instructions.          │"
echo "└─────────────────────────────────────────────────────┘"
echo ""
